name: PHP Composer

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Server
        run: |
          sudo groupadd -r -g 1002 c13
          sudo useradd -r -u 1001 -g 1002 -m -s /bin/bash c13
          whoami

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
